#!/bin/bash

function usage()
{
	printf "Miner Control\n\n"
	printf "Usage: miner [OPTION]\n\n"
	printf "start: Start Miner Service\n"
	printf "stop: Stop Miner Service\n"
	printf "restart: Restart Miner Service\n"

}

function start()
{

	SCREEN=$(screen -ls mrminer | grep mrminer | wc -l)
	[ "$SCREEN" -gt 1 ] && echo "Miner already running..." && exit

	echo "Miner Starting..."
	# screen -dm -S mrminer bash -c "/root/mrminer/boot/start"
	screen -dm -c /home/mrminer/screenrc.mrminer

	# export DISPLAY=:0

	# SIZE=$(DISPLAY=:0 xdpyinfo | perl -n -e 'print "".(($1/24)-10)."x".(($2/12)-15)."-0+0" if /dimensions:\s*(\d+)x(\d+)/')

	# urxvt -geometry $SIZE -name "Mr.Miner" -e sh -c "screen -x mrminer"

	# DISPLAY=:0 urxvt -geometry 70x80-0+0 -e bash -c "screen -x mrminer"
}


function stop()
{
	screens=`screen -ls mrminer | grep -E "[0-9]+\.mrminer" | cut -d. -f1 | awk '{print $1}'`

	if [[ -z $screens ]]; then
		echo "No miner screens found"
	else
		for pid in $screens; do
			echo "Stopping screen session: $pid.mrminer"
			screen -S $pid -X quit
		done
	fi
}



case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)

		echo "Restarting miner"
		stop
		sleep 1
		start
	;;
	*)
		usage
	;;
esac
