#!/bin/bash

# export DISPLAY=:0

SIZE=$(DISPLAY=:0 xdpyinfo | perl -n -e 'print "".(($1/24)-10)."x".(($2/12)-15)."-0+0" if /dimensions:\s*(\d+)x(\d+)/')

DISPLAY=:0 urxvt -geometry $SIZE -name "Mr.Miner" -e sh -c "screen -x mrminer"

# urxvt -geometry 70x80-0+0 -e sh -c "screen -x mrminer"